version: '3.8'

services:
  ai-relay-server:
    build: .
    container_name: ai-relay-server
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=4200
      - CLAUDE_ENDPOINT=http://localhost:5050
      - OLLAMA_ENDPOINT=http://localhost:4003
      - GITHUB_WEBHOOK_SECRET=ai-relay-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Networks removed - using host network mode